### ISSUE TITLE
Can't install with pip

### ISSUE THREAD

**Issue by AYastrebov** [bustleandflurry/bottle-api-json-formatting#1]
Can't install this package with pip

Here is my console output

Mac-Pro-Andrey:~ ayastrebov$ pip install --upgrade bottle-api-json-formatting
Downloading/unpacking bottle-api-json-formatting
  Could not find any downloads that satisfy the requirement bottle-api-json-formatting
Cleaning up...
No distributions at all found for bottle-api-json-formatting
Storing complete log in /Users/ayastrebov/.pip/pip.log

And here is the [log](https://gist.github.com/StonerHawk/6278751)

**Comment by bartlinga** [comment]
I'm encountering a lot of http errors when working with https://pypi.python.org right now. I'll check back later today.

**Comment by bartlinga** [comment]
Fixed an issue in the setup tools. Upload 0.0.8. Not sure what happened to past uploads or if they happened at all.
